spring.application.name=Project Management System
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/project_management
spring.datasource.username=postgres
spring.datasource.password=Suhel@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/project-management